### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [KafuuNeko/BiliDownload#1]
请问可以发布到 F-Droid 吗？谢谢！

**Comment by KafuuNeko** [comment]
您好，可以的，我将在近期更新支持收藏夹和历史记录快速下载后发布导F-Droid

**Comment by linsui** [comment]
非常感谢，打包提交的时候可以 @ 我

**Comment by KafuuNeko** [comment]
好的👌

**Comment by KafuuNeko** [comment]
您好，我已经将新版本发布到F-Droid
https://gitlab.com/kafuuneko/fdroiddata/-/commit/49054b0ba97394021ec4702500fa10b84bbae8ee

但由于F-Droid对发布的限制，我无法发布带有ffmpeg二进制库版本的BVD。
因此发布到f-droid上的是lite版：https://github.com/KafuuNeko/BiliDownload/tree/lite
此版本由于没有ffmpeg，因此不提供音频提取、视频封装格式转换、音视频码率以及编码信息显示

**Comment by linsui** [comment]
我们可以在构建 apk 的时候一起构建 FFmpeg，可以参考其他应用的方式，比如 [mpv 的脚本](https://github.com/mpv-android/mpv-android/blob/master/buildscripts/scripts/ffmpeg.sh) 或者 [atalk 的脚本](https://github.com/cmeng-git/atalk-android/tree/master/aTalk/jni/static_library_built/ffmpeg-x264)。

**Comment by KafuuNeko** [comment]
好的，我稍后试试看

**Comment by linsui** [comment]
https://gitlab.com/linsui/fdroiddata/-/commit/d7efcb251a258c063c93579ea97b5be35d7a36ed 我用 ffmpeg-android-maker 编译 FFmpeg，但调用 FFmpeg 就会出错。我猜需要使用 FFmpeg 4.4？GMS 是专有库，所以 F-Droid 不允许使用。似乎并没有使用，所以我直接去掉了。

**Comment by KafuuNeko** [comment]
是的，并没有使用到GMS

**Comment by linsui** [comment]
FFmpeg 4.4 没有问题，我开了个 [MR](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11211)。

**Comment by KafuuNeko** [comment]
好的，非常感谢！那么我可以删除之前的lite版本分支了，因为lite之前一直有些问题，所以我倒是没去merge

**Comment by KafuuNeko** [comment]
好的，已经合并了

**Comment by linsui** [comment]
啊，我是说如果您觉得 https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11211 没有问题我们可以现在就合并。也可以等到下个版本发布再合并。

**Comment by KafuuNeko** [comment]
噢噢，没问题的，我们可以现在就合并

**Comment by linsui** [comment]
好的 :ok_hand:

**Comment by linsui** [comment]
大概两到三天内会进入 F-Droid 存储库。这个是 F-Droid 的图标。

```
 [<img alt="Get it on F-Droid" src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png" width="240">](https://f-droid.org/packages/cc.kafuu.bilidownload)
```

 [<img alt="Get it on F-Droid" src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png" width="240">](https://f-droid.org/packages/cc.kafuu.bilidownload)

谢谢！

**Comment by KafuuNeko** [comment]
好的，辛苦您了！
