### ISSUE TITLE
登入后也无法下载1080p高码率和4k，最近突然间出现这个问题，换了几个版本都无济于事

### ISSUE THREAD

**Issue by zbsbs** [KafuuNeko/BiliDownload#10]

**Comment by yllhwa** [comment]
请问近期有发版计划吗？
（可以搞个github action编译cannary包😄）

**Comment by yllhwa** [comment]
刚编译了新版本，应该是跑不起来。
```java
JsonArray durl = data.getAsJsonArray("durl");
if (durl.size() == 0) {
    callback.failure("Video player source is empty");
    return;
}
```
只有MP4格式的视频才能返回durl，而DASH格式的视频（即分片视频）不会返回durl，详见[API 文档](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/video/videostream_url.md)

**Comment by KafuuNeko** [comment]
您好，我这周末我更新一下。上次的commit并没有解决次问题，就忙着处理别的事去了。

**Comment by KafuuNeko** [comment]
此问题已在β2.0.1版本解决[版本迭代：β2.0.1](https://github.com/KafuuNeko/BiliDownload/commit/068c94a917832363417183379448c0e710d7ea6a)
