### ISSUE TITLE
点击下载后闪退，已手动给了存储权限。

### ISSUE THREAD

**Issue by JUST-INTJ** [KafuuNeko/BiliDownload#14]
google play下的也同样。你们有没有?

**Comment by KafuuNeko** [comment]
目前我的测试机上没有出现这种情况，稍后我再测试一下。

**Comment by KafuuNeko** [comment]
重构版本错误无复现[β2.0.1](https://github.com/KafuuNeko/BiliDownload/commit/068c94a917832363417183379448c0e710d7ea6a)
