### ISSUE TITLE
下载视频显示【音频未提取】

### ISSUE THREAD

**Issue by Rorschach111** [KafuuNeko/BiliDownload#15]
登录后下载1080p高帧率视频，只有视频没有音频，显示音频未提取。play安装，小米14。

**Comment by KafuuNeko** [comment]
bilibili后台更新了，现在是音视频分流，我抽空更新一下吧

**Comment by KafuuNeko** [comment]
此问题已在β2.0.1版本解决[版本迭代：β2.0.1](https://github.com/KafuuNeko/BiliDownload/commit/068c94a917832363417183379448c0e710d7ea6a)
