### ISSUE TITLE
部分视频不能获取最高画质

### ISSUE THREAD

**Issue by rtxneko** [KafuuNeko/BiliDownload#17]
如题
貌似是睿站每个视频都有各种编码
然后部分老的编码（flv？）就直接没有高分分辨率（1080p及以上）的规格了

**Comment by KafuuNeko** [comment]
bilibili最近更新过，flv已经被淘汰了，bvd原本使用的下载方式不太适合新版的（音视频分流下载），因此旧版本没有对这方面进行兼容性更新，目前正在重构这个项目[develop](https://github.com/KafuuNeko/BiliDownload/tree/develop)，重构后可以解决这些问题，

**Comment by dareps** [comment]
> bilibili最近更新过，flv已经被淘汰了，bvd原本使用的下载方式不太适合新版的（音视频分流下载），因此旧版本没有对这方面进行兼容性更新，目前正在重构这个项目[develop](https://github.com/KafuuNeko/BiliDownload/tree/develop)，重构后可以解决这些问题，

请问重构的进度条走到哪呢？
我已迫不及待想要使用了。😶‍🌫️😄

**Comment by KafuuNeko** [comment]
目前已经完成视频搜索、下载[develop](https://github.com/KafuuNeko/BiliDownload/tree/develop)，还差下载记录管理、登录以及个人主页模块，预估这个月可以全部完成并发布2.0
