### ISSUE TITLE
这一版无法像前一版可以直接贴入b站的分享链接搜寻出视频，建议还是要可以贴上b站的分享链接后直接搜出

### ISSUE THREAD

**Issue by liuxb99** [KafuuNeko/BiliDownload#18]
这一版无法像前一般可以直接贴入b站的分享链接搜寻出视频，建议还是要可以贴上b站的分享链接后直接搜出

**Comment by KafuuNeko** [comment]
已经解决此问题：[搜索支持直接解析分享链接、bvid、avid、ss、ep](https://github.com/KafuuNeko/BiliDownload/commit/32b979c37c9e3c9b55cd69b9e383ebb87e069a63)

**Comment by KafuuNeko** [comment]
2.1.3已支持直接解析分享链接
