### ISSUE TITLE
报错如图

### ISSUE THREAD

**Issue by liuxb99** [KafuuNeko/BiliDownload#19]
报错入图
![Screenshot_20240729_103812_BVD](https://github.com/user-attachments/assets/f815db2e-d08e-449c-b30f-044c89ff6a72)

**Comment by KafuuNeko** [comment]
已解决此报错：[解决无法解析部分视频问题](https://github.com/KafuuNeko/BiliDownload/commit/51009e06365c8fb2f772c29c5b3fcd916bbfdd83)

**Comment by KafuuNeko** [comment]
2.1.3已解决报错问题
