### ISSUE TITLE
深色模式闪退

### ISSUE THREAD

**Issue by ricofx47** [KafuuNeko/BiliDownload#2]
系统开启深色模式软件会闪退，仅在我的手机上测试过。
![Screenshot_2022-05-15-09-03-52-795_com android settings](https://user-images.githubusercontent.com/29699145/168453020-9d9cab6d-ce38-416d-a9e7-e43dc99147c5.jpg)

**Comment by KafuuNeko** [comment]
感谢反馈，我已经解决了这个问题，请等待新版本发布
