### ISSUE TITLE
搜索的一些bug

### ISSUE THREAD

**Issue by xiaoxiyao** [KafuuNeko/BiliDownload#22]
在视频下搜索“凡人”
![Screenshot_2024-08-27-10-11-22-865_cc.kafuu.bilidownload.jpg](https://github.com/user-attachments/assets/8c0bd5b7-bbf8-4796-869f-83ff2a63228a)

切换到番剧，点击搜索结果
![Screenshot_2024-08-27-10-11-38-423_cc.kafuu.bilidownload.jpg](https://github.com/user-attachments/assets/fe497364-97c8-46e5-b220-22105149586d)

**Comment by KafuuNeko** [comment]
返回数据解析错误，此数据未被使用到，已删除解决：[fix: 删除无用的api返回数据](https://github.com/KafuuNeko/BiliDownload/commit/57af4191b7ea001a4cdc79ed3bc9cfbde0eb20d7)

**Comment by KafuuNeko** [comment]
已解决
