### ISSUE TITLE
下载时使用的Headers设置UA有误，会被拦截

### ISSUE THREAD

**Issue by yllhwa** [KafuuNeko/BiliDownload#4]
https://github.com/KafuuNeko/BiliDownload/blob/9ccb9ccff5a906c705a0a877842eb2a6afa1b985/app/src/main/java/cc/kafuu/bilidownload/bilibili/Bili.java#L47-L54
此处downloadHeaders使用小写的user-agent是有什么特殊考虑吗？  
经测试若使用小写的user-agent，系统(MIUI13)会设置大写的User-Agent:`AndroidDownloadManager/12 (Linux; U; Android 12; M2007J3SC Build/SKQ1.211006.001)`，从而会被b站拦截(403 Forbidden)无法下载。
修改为大写后功能恢复正常。
顺便感谢开发该工具！

**Comment by KafuuNeko** [comment]
您好，感谢反馈问题。
这里是小写是因为当时我抓包时使用的浏览器是edge，此浏览器的开发者工具中是小写显示的，因此我在拷贝到代码的UA请求头域是小写的。
关于MIUI13的问题，可能是因为MIUI13的DownloadManager在检测某请求头域是否存在时是大小写敏感的，全小写的请求头域可能被判定为不存在而自动添加了DownloadManager的UA。因此在下版本中所有请求头域都将改为默认首字母大写以避免此类问题。

**Comment by yllhwa** [comment]
忘记close了233
已经用了几个月了，确实好用♥
